### ISSUE TITLE
ELIFECYCLE: Cannot find module './lib/PostgresStroage'

### ISSUE THREAD

**Issue by roeintense** [TDAmeritrade/botbuilder-storage-postgres#4]
```
Error: Cannot find module './lib/PostgresStorage'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lop135/repo/betterbot-botkit-4/node_modules/botbuilder-storage-postgres/index.js:1:85)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Expect it is something in typescript compilation that is missing.

**Comment by roeintense** [comment]
Was goofing the dist publication on `npm publish` because I'm a noob. Ignored `lib/` in `.gitignore`, but allowed in `.npmignore`. Yeehaw.
